<?php /*a:2:{s:77:"/mnt/hgfs/centosVM/Manage_WXRobot_Web/application/admin/view/login/index.html";i:1609961110;s:77:"/mnt/hgfs/centosVM/Manage_WXRobot_Web/application/admin/view/index/index.html";i:1641362166;}*/ ?>
<!DOCTYPE html><html lang="zh"><head><title><?php echo htmlentities((isset($title) && ($title !== '')?$title:'')); if(!empty($title)): ?> · <?php endif; ?><?php echo sysconf('site_name'); ?></title><meta charset="utf-8"><meta name="renderer" content="webkit"><meta name="format-detection" content="telephone=no"><meta name="apple-mobile-web-app-capable" content="yes"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><meta name="apple-mobile-web-app-status-bar-style" content="black"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=0.4"><link rel="shortcut icon" href="<?php echo sysconf('site_icon'); ?>"><link rel="stylesheet" href="/static/plugs/awesome/fonts.css?at=<?php echo date('md'); ?>"><link rel="stylesheet" href="/static/plugs/layui/css/layui.css?at=<?php echo date('md'); ?>"><link rel="stylesheet" href="/static/theme/css/console.css?at=<?php echo date('md'); ?>"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><script>if (location.href.indexOf('#') > -1) location.replace(location.href.split('#')[0])</script><link rel="stylesheet" href="/static/theme/css/login.css"><script>window.ROOT_URL = '';</script><script src="/static/plugs/jquery/pace.min.js"></script><style>        .layui-badge {
            border-radius: 50%;
            top:10px!important;
        }
    </style></head><body class="layui-layout-body"><div class="login-container" data-supersized="/static/theme/img/login/bg1.jpg,/static/theme/img/login/bg2.jpg"><div class="header notselect layui-hide-xs"><a href="<?php echo url('@'); ?>" class="title"><?php echo sysconf('app_name'); ?><span class="padding-left-5 font-s10"><?php echo sysconf('app_version'); ?></span></a><?php if(!(empty($devmode) || (($devmode instanceof \think\Collection || $devmode instanceof \think\Paginator ) && $devmode->isEmpty()))): ?><a class="pull-right layui-anim layui-anim-fadein" href='https://gitee.com/zoujingli/ThinkAdmin'><img src='https://gitee.com/zoujingli/ThinkAdmin/widgets/widget_1.svg' alt='Fork me on Gitee'></a><?php endif; ?></div><form data-login-form onsubmit="return false" method="post" class="layui-anim layui-anim-upbit" autocomplete="off"><h2 class="notselect">System Management</h2><ul><li class="username"><label><i class="layui-icon layui-icon-username"></i><input class="layui-input" required pattern="^\S{4,}$" name="username" autofocus autocomplete="off" placeholder="Username" title="Please input Username"></label></li><li class="password"><label><i class="layui-icon layui-icon-password"></i><input class="layui-input" required pattern="^\S{4,}$" name="password" maxlength="32" type="password" autocomplete="off" placeholder="Password" title="Please enter your password"></label></li><li class="verify layui-hide"><label class="inline-block relative"><i class="layui-icon layui-icon-picture-fine"></i><input class="layui-input" required pattern="^\S{4,}$" name="verify" value="<?php echo htmlentities($captcha->getCode()); ?>" maxlength="4" autocomplete="off" placeholder="Verification code" title="please enter verification code"></label><img data-refresh-captcha alt="img" src="<?php echo htmlentities($captcha->getData()); ?>"><input type="hidden" name="uniqid" value="<?php echo htmlentities($captcha->getUniqid()); ?>"></li><li class="text-center padding-top-20"><input type="hidden" name="skey" value="<?php echo htmlentities((isset($loginskey) && ($loginskey !== '')?$loginskey:'')); ?>"><button type="submit" class="layui-btn layui-disabled full-width" data-form-loaded="Sign in">loading</button></li></ul></form><div class="footer notselect"><p class="layui-hide-xs"><a target="_blank" href="https://www.google.cn/chrome">Google Chrome is recommended</a></p><?php echo sysconf('site_copy'); ?></div></div><script src="/static/plugs/layui/layui.all.js"></script><script src="/static/plugs/require/require.js"></script><script src="/static/admin.js"></script><script src="/static/plugs/supersized/supersized.3.2.7.min.js"></script></body><script type="text/javascript" charset="utf-8">    // $(function(){
    //         $.get("/admin/robot/GetLoggedAccountList");
    //         setInterval(function (){
    //             $.get("/admin/robot/GetLoggedAccountList");
    //         } , 20000)
    //     })
</script></html>