name: sync-Koishi
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Koishi
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync-Koishi
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/koishijs/koishi"
          source_branch: "master"
          destination_branch: "Koishi"
          github_token: ${{ secrets.PAT }}
